
services:
  app:
    build: . # Constrói a imagem a partir do Dockerfile na raiz do projeto
    container_name: api # Nome do container
    ports:
      - "8000:8000" # Mapeia a porta 8000 do container para a porta 8000 do host
    volumes:
      - .:/app # Monta o diretório atual, em /app dentro do container.
               # Isso permite que as alterações no código sejam refletidas imediatamente devido ao --reload do uvicorn.
    
   
